# Generated by Django 5.2.1 on 2025-07-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='syllabus',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
