# Generated by Django 5.2.1 on 2025-07-03 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subjects_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='semesters',
        ),
        migrations.RemoveField(
            model_name='branches',
            name='year',
        ),
        migrations.AddField(
            model_name='subjects',
            name='elective',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branches',
            name='branchCode',
            field=models.TextField(max_length=4),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(max_length=2)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branches', verbose_name='branch')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.TextField(max_length=7)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branches', verbose_name='branch')),
            ],
            options={
                'verbose_name': 'Year',
                'verbose_name_plural': 'Years',
            },
        ),
    ]
