# Generated by Django 5.2.1 on 2025-07-03 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_branches_semesters_remove_branches_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='year',
            name='branch',
        ),
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AddField(
            model_name='year',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
