# Generated by Django 5.2.1 on 2025-07-03 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_semester_branch_remove_year_branch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'ordering': ['subjectCode'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='elective',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='subjects',
            name='category',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='effectiveFrom',
            field=models.CharField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='sem',
            field=models.IntegerField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branches',
            name='branchCode',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='branches',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='shortform',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branches', verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subjectCode',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='years',
            field=models.CharField(max_length=7),
        ),
    ]
