# Generated by Django 5.2.1 on 2025-07-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_subjects_options_remove_subjects_elective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='years',
            field=models.CharField(default=None, max_length=7),
        ),
    ]
