# Generated by Django 5.2.1 on 2025-07-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_year_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='effectiveFrom',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='year',
            name='years',
            field=models.CharField(max_length=7),
        ),
    ]
