# Generated by Django 5.2.1 on 2025-07-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_subjects_effectivefrom_alter_year_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='effectiveFrom',
        ),
    ]
