# Generated by Django 5.2.1 on 2025-07-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_subjects_effectivefrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='effectiveFrom',
            field=models.CharField(default=None, max_length=7),
        ),
        migrations.AlterField(
            model_name='year',
            name='years',
            field=models.CharField(default=None, max_length=7),
        ),
    ]
