# Generated by Django 5.2.1 on 2025-07-03 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_subjects_effectivefrom_alter_year_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.branches', verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sem',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='year',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
