# Generated by Django 5.2.1 on 2025-07-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_branches_course_alter_semester_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='year',
            name='course',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='course',
        ),
        migrations.DeleteModel(
            name='Branches',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
