# Generated by Django 5.2.1 on 2025-07-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Year',
        ),
    ]
