# Generated by Django 5.2.1 on 2025-07-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_subjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
