# Generated by Django 5.2.1 on 2025-07-03 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
