# Generated by Django 5.2.1 on 2025-07-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_branches_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branches',
        ),
    ]
