# Generated by Django 5.2.1 on 2025-07-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_delete_branches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
