# Generated by Django 5.2.1 on 2025-07-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='effectiveFrom',
            field=models.CharField(default=None, max_length=7),
        ),
    ]
