# Generated by Django 5.2.1 on 2025-07-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_subjects_effectivefrom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='years',
        ),
        migrations.AddField(
            model_name='year',
            name='year',
            field=models.CharField(default=None, max_length=7),
        ),
    ]
