# Generated by Django 5.2.1 on 2025-07-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_year_years_year_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='effectiveFrom',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
