# Generated by Django 5.2.1 on 2025-07-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_subjects_effectivefrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='credit',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
