# Generated by Django 5.2.1 on 2025-07-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_semester_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subjectCode',
            field=models.CharField(max_length=100),
        ),
    ]
